/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AArrayAsmtStmt extends PStmt
{
    private TId _name_;
    private TLbracket _lbracket_;
    private PExp _idx_;
    private TRbracket _rbracket_;
    private TAsmt _asmt_;
    private PExp _val_;
    private TSemi _semi_;

    public AArrayAsmtStmt()
    {
        // Constructor
    }

    public AArrayAsmtStmt(
        @SuppressWarnings("hiding") TId _name_,
        @SuppressWarnings("hiding") TLbracket _lbracket_,
        @SuppressWarnings("hiding") PExp _idx_,
        @SuppressWarnings("hiding") TRbracket _rbracket_,
        @SuppressWarnings("hiding") TAsmt _asmt_,
        @SuppressWarnings("hiding") PExp _val_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setName(_name_);

        setLbracket(_lbracket_);

        setIdx(_idx_);

        setRbracket(_rbracket_);

        setAsmt(_asmt_);

        setVal(_val_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AArrayAsmtStmt(
            cloneNode(this._name_),
            cloneNode(this._lbracket_),
            cloneNode(this._idx_),
            cloneNode(this._rbracket_),
            cloneNode(this._asmt_),
            cloneNode(this._val_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayAsmtStmt(this);
    }

    public TId getName()
    {
        return this._name_;
    }

    public void setName(TId node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TLbracket getLbracket()
    {
        return this._lbracket_;
    }

    public void setLbracket(TLbracket node)
    {
        if(this._lbracket_ != null)
        {
            this._lbracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lbracket_ = node;
    }

    public PExp getIdx()
    {
        return this._idx_;
    }

    public void setIdx(PExp node)
    {
        if(this._idx_ != null)
        {
            this._idx_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idx_ = node;
    }

    public TRbracket getRbracket()
    {
        return this._rbracket_;
    }

    public void setRbracket(TRbracket node)
    {
        if(this._rbracket_ != null)
        {
            this._rbracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rbracket_ = node;
    }

    public TAsmt getAsmt()
    {
        return this._asmt_;
    }

    public void setAsmt(TAsmt node)
    {
        if(this._asmt_ != null)
        {
            this._asmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._asmt_ = node;
    }

    public PExp getVal()
    {
        return this._val_;
    }

    public void setVal(PExp node)
    {
        if(this._val_ != null)
        {
            this._val_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._val_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._lbracket_)
            + toString(this._idx_)
            + toString(this._rbracket_)
            + toString(this._asmt_)
            + toString(this._val_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._lbracket_ == child)
        {
            this._lbracket_ = null;
            return;
        }

        if(this._idx_ == child)
        {
            this._idx_ = null;
            return;
        }

        if(this._rbracket_ == child)
        {
            this._rbracket_ = null;
            return;
        }

        if(this._asmt_ == child)
        {
            this._asmt_ = null;
            return;
        }

        if(this._val_ == child)
        {
            this._val_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TId) newChild);
            return;
        }

        if(this._lbracket_ == oldChild)
        {
            setLbracket((TLbracket) newChild);
            return;
        }

        if(this._idx_ == oldChild)
        {
            setIdx((PExp) newChild);
            return;
        }

        if(this._rbracket_ == oldChild)
        {
            setRbracket((TRbracket) newChild);
            return;
        }

        if(this._asmt_ == oldChild)
        {
            setAsmt((TAsmt) newChild);
            return;
        }

        if(this._val_ == oldChild)
        {
            setVal((PExp) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
