/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AFormal extends PFormal
{
    private PType _kind_;
    private TId _name_;

    public AFormal()
    {
        // Constructor
    }

    public AFormal(
        @SuppressWarnings("hiding") PType _kind_,
        @SuppressWarnings("hiding") TId _name_)
    {
        // Constructor
        setKind(_kind_);

        setName(_name_);

    }

    @Override
    public Object clone()
    {
        return new AFormal(
            cloneNode(this._kind_),
            cloneNode(this._name_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFormal(this);
    }

    public PType getKind()
    {
        return this._kind_;
    }

    public void setKind(PType node)
    {
        if(this._kind_ != null)
        {
            this._kind_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kind_ = node;
    }

    public TId getName()
    {
        return this._name_;
    }

    public void setName(TId node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kind_)
            + toString(this._name_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kind_ == child)
        {
            this._kind_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kind_ == oldChild)
        {
            setKind((PType) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
