/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AIntarrayType extends PType
{
    private TInt _int1_;
    private PArray _array_;

    public AIntarrayType()
    {
        // Constructor
    }

    public AIntarrayType(
        @SuppressWarnings("hiding") TInt _int1_,
        @SuppressWarnings("hiding") PArray _array_)
    {
        // Constructor
        setInt1(_int1_);

        setArray(_array_);

    }

    @Override
    public Object clone()
    {
        return new AIntarrayType(
            cloneNode(this._int1_),
            cloneNode(this._array_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntarrayType(this);
    }

    public TInt getInt1()
    {
        return this._int1_;
    }

    public void setInt1(TInt node)
    {
        if(this._int1_ != null)
        {
            this._int1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._int1_ = node;
    }

    public PArray getArray()
    {
        return this._array_;
    }

    public void setArray(PArray node)
    {
        if(this._array_ != null)
        {
            this._array_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._array_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._int1_)
            + toString(this._array_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._int1_ == child)
        {
            this._int1_ = null;
            return;
        }

        if(this._array_ == child)
        {
            this._array_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._int1_ == oldChild)
        {
            setInt1((TInt) newChild);
            return;
        }

        if(this._array_ == oldChild)
        {
            setArray((PArray) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
