/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class ALengthFunction extends PFunction
{
    private PBracdot _bracdot_;
    private TDot _dot_;
    private TLength _length_;

    public ALengthFunction()
    {
        // Constructor
    }

    public ALengthFunction(
        @SuppressWarnings("hiding") PBracdot _bracdot_,
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") TLength _length_)
    {
        // Constructor
        setBracdot(_bracdot_);

        setDot(_dot_);

        setLength(_length_);

    }

    @Override
    public Object clone()
    {
        return new ALengthFunction(
            cloneNode(this._bracdot_),
            cloneNode(this._dot_),
            cloneNode(this._length_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALengthFunction(this);
    }

    public PBracdot getBracdot()
    {
        return this._bracdot_;
    }

    public void setBracdot(PBracdot node)
    {
        if(this._bracdot_ != null)
        {
            this._bracdot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bracdot_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public TLength getLength()
    {
        return this._length_;
    }

    public void setLength(TLength node)
    {
        if(this._length_ != null)
        {
            this._length_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._length_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bracdot_)
            + toString(this._dot_)
            + toString(this._length_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bracdot_ == child)
        {
            this._bracdot_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._length_ == child)
        {
            this._length_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bracdot_ == oldChild)
        {
            setBracdot((PBracdot) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._length_ == oldChild)
        {
            setLength((TLength) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
