/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AMult1Mult extends PMult
{
    private PNotexp _notexp_;

    public AMult1Mult()
    {
        // Constructor
    }

    public AMult1Mult(
        @SuppressWarnings("hiding") PNotexp _notexp_)
    {
        // Constructor
        setNotexp(_notexp_);

    }

    @Override
    public Object clone()
    {
        return new AMult1Mult(
            cloneNode(this._notexp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMult1Mult(this);
    }

    public PNotexp getNotexp()
    {
        return this._notexp_;
    }

    public void setNotexp(PNotexp node)
    {
        if(this._notexp_ != null)
        {
            this._notexp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notexp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._notexp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._notexp_ == child)
        {
            this._notexp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._notexp_ == oldChild)
        {
            setNotexp((PNotexp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
