/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class ANotandExp extends PExp
{
    private PLessthan _lessthan_;

    public ANotandExp()
    {
        // Constructor
    }

    public ANotandExp(
        @SuppressWarnings("hiding") PLessthan _lessthan_)
    {
        // Constructor
        setLessthan(_lessthan_);

    }

    @Override
    public Object clone()
    {
        return new ANotandExp(
            cloneNode(this._lessthan_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotandExp(this);
    }

    public PLessthan getLessthan()
    {
        return this._lessthan_;
    }

    public void setLessthan(PLessthan node)
    {
        if(this._lessthan_ != null)
        {
            this._lessthan_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lessthan_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lessthan_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lessthan_ == child)
        {
            this._lessthan_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lessthan_ == oldChild)
        {
            setLessthan((PLessthan) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
