/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class ANotlessthanLessthan extends PLessthan
{
    private PMinusplus _minusplus_;

    public ANotlessthanLessthan()
    {
        // Constructor
    }

    public ANotlessthanLessthan(
        @SuppressWarnings("hiding") PMinusplus _minusplus_)
    {
        // Constructor
        setMinusplus(_minusplus_);

    }

    @Override
    public Object clone()
    {
        return new ANotlessthanLessthan(
            cloneNode(this._minusplus_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotlessthanLessthan(this);
    }

    public PMinusplus getMinusplus()
    {
        return this._minusplus_;
    }

    public void setMinusplus(PMinusplus node)
    {
        if(this._minusplus_ != null)
        {
            this._minusplus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusplus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minusplus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minusplus_ == child)
        {
            this._minusplus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minusplus_ == oldChild)
        {
            setMinusplus((PMinusplus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
