/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class APlusMinusplus extends PMinusplus
{
    private PMinusplus _minusplus_;
    private TPlus _plus_;
    private PMult _mult_;

    public APlusMinusplus()
    {
        // Constructor
    }

    public APlusMinusplus(
        @SuppressWarnings("hiding") PMinusplus _minusplus_,
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PMult _mult_)
    {
        // Constructor
        setMinusplus(_minusplus_);

        setPlus(_plus_);

        setMult(_mult_);

    }

    @Override
    public Object clone()
    {
        return new APlusMinusplus(
            cloneNode(this._minusplus_),
            cloneNode(this._plus_),
            cloneNode(this._mult_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusMinusplus(this);
    }

    public PMinusplus getMinusplus()
    {
        return this._minusplus_;
    }

    public void setMinusplus(PMinusplus node)
    {
        if(this._minusplus_ != null)
        {
            this._minusplus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusplus_ = node;
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PMult getMult()
    {
        return this._mult_;
    }

    public void setMult(PMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minusplus_)
            + toString(this._plus_)
            + toString(this._mult_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minusplus_ == child)
        {
            this._minusplus_ = null;
            return;
        }

        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minusplus_ == oldChild)
        {
            setMinusplus((PMinusplus) newChild);
            return;
        }

        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((PMult) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
