/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import java.util.*;
import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private PMainClass _main_;
    private final LinkedList<PClassDecl> _rest_ = new LinkedList<PClassDecl>();

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") PMainClass _main_,
        @SuppressWarnings("hiding") List<?> _rest_)
    {
        // Constructor
        setMain(_main_);

        setRest(_rest_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneNode(this._main_),
            cloneList(this._rest_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public PMainClass getMain()
    {
        return this._main_;
    }

    public void setMain(PMainClass node)
    {
        if(this._main_ != null)
        {
            this._main_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._main_ = node;
    }

    public LinkedList<PClassDecl> getRest()
    {
        return this._rest_;
    }

    public void setRest(List<?> list)
    {
        for(PClassDecl e : this._rest_)
        {
            e.parent(null);
        }
        this._rest_.clear();

        for(Object obj_e : list)
        {
            PClassDecl e = (PClassDecl) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._rest_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._main_)
            + toString(this._rest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._main_ == child)
        {
            this._main_ = null;
            return;
        }

        if(this._rest_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._main_ == oldChild)
        {
            setMain((PMainClass) newChild);
            return;
        }

        for(ListIterator<PClassDecl> i = this._rest_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PClassDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
